[project]
name = "human-capture"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.6"
dependencies = [
    "fastapi>=0.115.12",
    "mediapipe>=0.10.21",
    "opencv-python>=4.11.0.86",
    "uvicorn>=0.34.0",
]
